config/routes.rb
Rails.application.routes.draw do

  root to: "tweets#index"

  devise_for :users
  resources :tweets do
    resources :comments, except: [:index]
  end
  resources :likes, only: [:create]
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates_presence_of :comment, :user_id, :tweet_id
  validates :comment_count, numericality: {greater_than_or_equal_to: 0}
  validates :likes_count, numericality: {greater_than_or_equal_to: 0}

  default_scope { order('created_at desc') }

  after_create :increase_reply_count
  after_destroy :decrease_reply_count

  belongs_to :user
  belongs_to :tweet
  has_many :likes, as: :likeable, dependent: :destroy

  def increase_reply_count
    record = get_parent_record()
    record.update!(comment_count: record.comment_count + 1)
  end

  def decrease_reply_count
    record = get_parent_record()
    record.update!(comment_count: record.comment_count - 1)
  end

  def get_parent_record
    if self.parent_comment_id.nil?
      record = Tweet.find_by_id(self.tweet_id)
    else
      record = Comment.find_by_id(self.parent_comment_id)
    end
    return record
  end

end

app/models/like.rb
class Like < ApplicationRecord
  validates_presence_of :user_id, :likeable_type, :likeable_id

  after_create :increase_like_count
  after_destroy :decrease_like_count

  belongs_to :likeable, polymorphic: true

  def increase_like_count
    record = get_parent_record()
    record.update!(likes_count: record.likes_count + 1)
  end

  def decrease_like_count
    record = get_parent_record()
    record.update!(likes_count: record.likes_count - 1)
  end

  def get_parent_record
    if self.likeable_type == 'Tweet'
      record = Tweet.find_by_id(self.likeable_id)
    elsif self.likeable_type == 'Comment'
      record = Comment.find_by_id(self.likeable_id)
    end
    return record
  end
end

app/models/tweet.rb
class Tweet < ApplicationRecord
	enum status: [:DRAFT, :PUBLISHED, :DISCARDED]

  validates_length_of :tweet, :within => 1..280, :too_long => "Tweet length exeeded", :if => Proc.new { |tweet| tweet.tweet.present? }
  validates_presence_of :user_id
  validates :comment_count, numericality: {greater_than_or_equal_to: 0}
  validates :likes_count, numericality: {greater_than_or_equal_to: 0}

  default_scope {order('created_at desc')}

  mount_uploader :image_url, TweetImageUploader

  belongs_to :user
  has_many :comments
  has_many :likes, as: :likeable, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates_presence_of :user_name, :email

  def first_name             
    self.name.split.first
  end

  def last_name
    self.name.split.last
  end

  has_many :tweets
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  include DeviseWhitelist
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def new
    @tweet = Tweet.find_by(id: params[:tweet_id])
    @parent_comment_id = params[:parent_comment_id].present? ? params[:parent_comment_id] : nil
    @comment = Comment.new(tweet: @tweet)
  end

  def create
    @tweet = Tweet.find_by(id: params[:tweet_id])
    @comment = Comment.new(comment_params)
    @comment.parent_comment_id = params[:parent_comment_id] if params[:parent_comment_id].present?
    respond_to do |format|
      if @comment.save
        format.html { redirect_to tweet_path(@tweet.id), notice: "Comment created" }
      else
        format.html { redirect_to tweet_path(@tweet.id), notice: @comment.errors.full_messages.to_sentence }
      end
    end
  end

  def edit
    @tweet = Tweet.find_by_id(params[:tweet_id])
    @comment = Comment.find_by_id(params[:id])
  end

  def update
    @comment = Comment.find_by_id(params[:id])
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to tweet_path(params[:tweet_id]), notice: "Comment was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def show
    @tweet = Tweet.find_by_id(params[:tweet_id])
    @comment = Comment.unscoped.joins(:user).where(id: params[:id]).select("comments.id, comments.user_id, comments.comment, comments.created_at, users.name, users.user_name").first
    @replies = Comment.unscoped.joins(:user).where(tweet_id: params[:tweet_id], parent_comment_id: @comment.id).select("comments.id, comments.user_id, comments.likes_count, comments.comment_count, comments.comment, comments.created_at, users.name, users.user_name").order("comments.updated_at desc")
  end

  def destroy
    @comment = Comment.find_by(id: params[:id])
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to tweet_path(params[:tweet_id]), notice: "Comment was successfully destroyed." }
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:comment).merge(user_id: current_user.id, tweet_id: params[:tweet_id])
    end

end

app/controllers/concerns/devise_whitelist.rb
module DeviseWhitelist
  extend ActiveSupport::Concern

  included do
    before_action :configure_permitted_parameters, if: :devise_controller?       
  end
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :user_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :user_name])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_post

  def create
    record_likes = @record.likes.where(user_id: current_user.id)
    if record_likes.exists?
      record_likes.first.destroy
    else
      record_likes.create(user_id: current_user.id)
    end
    return render json: { success: true, likes_count: @record.likes_count }
    # respond_to do |format|
    #   format.html { redirect_to request.referrer }
    # end
  end

  private
  def find_post
    if params[:comment_id].present?
      @record = Comment.find_by_id(params[:comment_id])
    else
      @record = Tweet.find_by_id(params[:tweet_id])
    end
  end

end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_tweet, only: %i[ edit update destroy ]

  def index
    @new_tweet = Tweet.new
    @tweets = Tweet.unscoped.joins(:user).where(status: Tweet.statuses[:PUBLISHED]).select("tweets.id, tweets.user_id, tweets.tweet, tweets.likes_count, tweets.comment_count, tweets.image_url, tweets.created_at, users.name, users.user_name").order("tweets.created_at desc")
  end

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    respond_to do |format|
      if @tweet.save
        format.html { redirect_to tweets_path, notice: "Tweet was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: "Tweet was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @tweet.update(status: Tweet.statuses[:DISCARDED])
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: "Tweet was successfully destroyed." }
    end
  end

  def show
    @tweet = Tweet.unscoped.joins(:user).where(id: params[:id]).select("tweets.id, tweets.tweet, tweets.created_at, users.name, users.user_name").first
    @comments = Comment.unscoped.joins(:user).where("tweet_id = ? and parent_comment_id is null", params[:id]).select("comments.id, comments.user_id, comments.likes_count, comments.comment_count, comments.comment, comments.created_at, users.name, users.user_name").order("comments.updated_at desc")
  end

  def edit
  end

  private
    def set_tweet
      @tweet = Tweet.find_by_id(params[:id])
    end

    def tweet_params
      params.require(:tweet).permit(:tweet, :image_url).merge(user_id: current_user.id, status: Tweet.statuses[:PUBLISHED])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: [tweet, comment], local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  </br>
  <div class="field">
    <%= form.label :comment %>
    <%= form.text_area :comment, size: "50", placeholder: "What's your take?" %>
  </div>

  <% if @parent_comment_id.present? %>
    <%= hidden_field_tag :parent_comment_id, @parent_comment_id %> 
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<%= render partial: 'form', locals: {:tweet => @tweet, :comment => @comment, :parent_comment_id => (defined? @parent_comment_id) ? @parent_comment_id : nil } %>

app/views/comments/new.html.erb
<%= render partial: 'form', locals: {:tweet => @tweet, :comment => @comment, :parent_comment_id => @parent_comment_id} %>

app/views/comments/show.html.erb
<h2>Comment</h2>
<p>
  <strong> <%= @comment.name %> </strong> </br> @<%= @comment.user_name %>
  <div>
    <%= @comment.comment %>
  </div>
  <hr style="height:2px;border-width:0;color:gray;background-color:gray">
</p>

<%= link_to "Add a Reply =>", new_tweet_comment_path(tweet_id: @tweet.id, parent_comment_id: @comment.id), class: "btn btn-large" %> 
</br>
</br>


<table>

  <thead>
    <tr>
      <th>Replies</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @replies.each do |comment| %>
      <tr>
        <td> <strong> <%= comment.name %> </strong>  @<%= comment.user_name %> <td> <small>Submitted <%= time_ago_in_words(comment.created_at) %> ago</small>
      </tr>
      <tr>
        <td><%= comment.comment %></td>        
        <% if true && current_user.id == comment.user_id %>
          <td><%= link_to 'Edit', edit_tweet_comment_path(id: comment.id, tweet_id: @tweet.id) %></td>
          <td><%= link_to 'Destroy', tweet_comment_path(@tweet, comment), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
      <tr>
        <td><%= comment.comment_count %> <%= (comment.comment_count) == 1 ? 'Comment' : 'Comments'%></td>
        <td><%= comment.likes_count %> <%= (comment.likes_count) == 1 ? 'Like' : 'Likes'%></td>
        <td><%= button_to 'Like', likes_path(comment_id: comment.id), method: :post %> </td>
        <td><button onclick="show_comment(<%= @tweet.id %>, <%= comment.id %>)"> Reply </button></td> 
      </tr>
    <% end %>
  </tbody>
</table>

</br> </br>

<%= link_to 'Back', tweets_path %>

<script type="text/javascript">
  function show_comment(tweet_id, comment_id) {
    location.href = "/tweets/" + tweet_id + "/comments/" + comment_id
  }
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p> 
    <p class="alert"><%= alert %></p>
    
    <% if current_user %>
      <%= link_to 'Log out', destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to 'Log in', new_user_session_path %>
      <%= link_to 'Register', new_user_registration_path %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet, local: true) do |form| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% tweet.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :tweet %>
    <%= form.text_area :tweet, size: "50", placeholder: "What's Happening?" %>
  </div>

  <div class="field">
    <%= form.file_field :image_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<h1>Home</h1>
<%= render 'form', tweet: @new_tweet %>
<hr style="height:2px;border-width:0;color:gray;background-color:gray">
</br>

<table>

  <thead>
    <tr>
      <th>My Feed</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td> <strong> <%= tweet.name %> </strong>  @<%= tweet.user_name %><td> <small>Submitted <%= time_ago_in_words(tweet.created_at) %> ago</small>
      </tr>
      <tr>
        <td onclick='show_tweet(<%= tweet.id %>)' style="cursor:pointer" ><%= tweet.tweet %></td>
        <% if current_user.id == tweet.user_id %>
          <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
          <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
      <% if tweet.image_url.present? %>
        <tr>
          <td> <%= image_tag(tweet.image_url.url, :size => '300x240') %> </td>
        </tr>
      <% end %>
      <tr>
        <td><%= tweet.comment_count %> <%= (tweet.comment_count) == 1 ? 'Comment' : 'Comments'%></td>
        <td id='like_count'><%= tweet.likes_count %> <%= (tweet.likes_count) == 1 ? 'Like' : 'Likes'%></td>
        <% if false %>
          <td><%= button_to 'Like', likes_path(tweet_id: tweet.id), method: :post %> </td>
        <% end %>
        <td><button onclick="like_post(<%= tweet.id %>)">Like</button> </td>
        <td><button onclick="show_tweet(<%= tweet.id %>)"> Comment </button></td> 
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<script type="text/javascript">
  function show_tweet(tweet_id) {
    location.href = "/tweets/"+tweet_id
  }

  function like_post(id) {
    $.ajax({
      url: "/likes",
      type: "post",
      data: { tweet_id: id },
      success: function(data) { 
        console.log(data.likes_count)
        $('#like_count').html(data.likes_count);
       },
      error: function(data) {}
    })
  }
</script>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form', tweet: @tweet %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<h2>Tweet</h2>
<p>
  <strong> <%= @tweet.name %> </strong> </br> @<%= @tweet.user_name %>
  <div>
    <%= @tweet.tweet %>
  </div>
  <hr style="height:2px;border-width:0;color:gray;background-color:gray">
</p>

<%= link_to "Add a comment =>", new_tweet_comment_path(tweet_id: @tweet.id), class: "btn btn-large" %> 
</br>
</br>


<table>

  <thead>
    <tr>
      <th>Comments</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td> <strong> <%= comment.name %> </strong>  @<%= comment.user_name %> <td> <small>Submitted <%= time_ago_in_words(comment.created_at) %> ago</small>
      </tr>
      <tr>
        <td><%= comment.comment %></td>        
        <% if current_user.id == comment.user_id %>
          <td><%= link_to 'Edit', edit_tweet_comment_path(comment_id: comment.id, tweet_id: @tweet.id) %></td>
          <td><%= link_to 'Destroy', tweet_comment_path(@tweet, comment), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
      <tr>
        <td><%= comment.comment_count %> <%= (comment.comment_count) == 1 ? 'Comment' : 'Comments'%></td>
        <td><%= comment.likes_count %> <%= (comment.likes_count) == 1 ? 'Like' : 'Likes'%></td>
        <td><%= button_to 'Like', likes_path(comment_id: comment.id), method: :post %> </td>
        <td><button onclick="show_comment(<%= @tweet.id %>, <%= comment.id %>)"> Reply </button></td> 
      </tr>
    <% end %>
  </tbody>
</table>

</br> </br>
<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>

<script type="text/javascript">
  function show_comment(tweet_id, comment_id) {
    location.href = tweet_id + "/comments/" + comment_id
  }
</script>